#ifndef _BG_PALETTES_H_
#define _BG_PALETTES_H_

#define BGPAL(x) ((x)<<12)

#define HUD_PALETTE_NUM 12
#define ENEMY_DB_PALETTE_NUM 13
#define HUD_BUTTON_PALETTE_NUM 11
#define MINIMAP_PALETTE_NUM 14
#define MINIMAP_SPECIAL_PALETTE_NUM 10 
#define ALL_BLACK_PAL_NUM 9


#define SUB_ITEMS_PAL 1
#define SUB_LOCKS_PAL 0

#define HUD_PAL BGPAL(HUD_PALETTE_NUM)
#define ENEMY_DB_PAL BGPAL(ENEMY_DB_PALETTE_NUM)
#define BUTTON_PAL BGPAL(HUD_BUTTON_PALETTE_NUM)
#define MINIMAP_PAL BGPAL(MINIMAP_PALETTE_NUM)
#define MINIMAP_SPECIAL_PAL BGPAL(MINIMAP_SPECIAL_PALETTE_NUM)

#define BG_TEXT_NUM 0
#define BG_MID_NUM 1
#define BG_FOREGROUND_NUM 2
#define BG_MAIN_NUM 3

#define BG_TEXT DISPLAY_BG0_ACTIVE
#define BG_MID DISPLAY_BG1_ACTIVE
#define BG_FOREGROUND DISPLAY_BG2_ACTIVE
#define BG_MAIN DISPLAY_BG3_ACTIVE



#endif


